title: tukasa's profile
timezone: Asia/Tokyo
logo: /assets/img/logo.png
description: non ridere, non lugere, neque detestari, sed intelligere
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
